--- Quest Script: Rune Mythos
--- Generated by the Nexus Quest Builder

local API        = require("api")
local QUEST      = require("quests.quest")
local LODESTONES = require("Lodestones")
local QS         = require("quests.QuestScript")

local qs = QS.new({
    name  = "Rune Mythos",
    debug = true,
})

-- Item / object IDs (fill in as needed)
local ITEM = {}
local OBJ  = {}

-- smartWalk: teleports to the nearest lodestone if it shortens the trip
local _SW_LODES = {
    {n='AL_KHARID',          x=3297, y=3184, z=0},
    {n='ANACHRONIA',         x=5431, y=2338, z=0},
    {n='ARDOUGNE',           x=2634, y=3348, z=0},
    {n='ASHDALE',            x=2474, y=2708, z=2},
    {n='BANDIT_CAMP',        x=2899, y=3544, z=0},
    {n='BURTHOPE',           x=2899, y=3544, z=0},
    {n='CANIFIS',            x=3517, y=3515, z=0},
    {n='CATHERBY',           x=2811, y=3449, z=0},
    {n='DRAYNOR_VILLAGE',    x=3105, y=3298, z=0},
    {n='EAGLES_PEAK',        x=2366, y=3479, z=0},
    {n='EDGEVILLE',          x=3067, y=3505, z=0},
    {n='FALADOR',            x=2967, y=3403, z=0},
    {n='FORT_FORINTHRY',     x=3298, y=3525, z=0},
    {n='FREMENNIK_PROVINCE', x=2712, y=3677, z=0},
    {n='KARAMJA',            x=2761, y=3147, z=0},
    {n='LUNAR_ISLE',         x=2085, y=3914, z=0},
    {n='LUMBRIDGE',          x=3233, y=3221, z=0},
    {n='MENAPHOS',           x=3216, y=2716, z=0},
    {n='OOGLOG',             x=2532, y=2871, z=0},
    {n='PORT_SARIM',         x=3011, y=3215, z=0},
    {n='PRIFDDINAS',         x=2208, y=3360, z=1},
    {n='SEERS_VILLAGE',      x=2689, y=3482, z=0},
    {n='TAVERLEY',           x=2878, y=3442, z=0},
    {n='TIRANNWN',           x=2254, y=3149, z=0},
    {n='UM',                 x=1084, y=1768, z=1},
    {n='VARROCK',            x=3214, y=3376, z=0},
    {n='YANILLE',            x=2560, y=3094, z=0},
}
local function smartWalk(dx, dy, dz, tol)
    local p = API.PlayerCoord()
    local d2dest = math.sqrt((p.x-dx)^2+(p.y-dy)^2)
    local bestL, bestD = nil, math.huge
    for _, l in ipairs(_SW_LODES) do
        local d = math.sqrt((l.x-dx)^2+(l.y-dy)^2)
        if d < bestD then bestD=d; bestL=l end
    end
    if bestL and bestD < d2dest then
        API.logInfo('[QUEST] smartWalk: '..bestL.n..' d='..math.floor(bestD)..' < '..math.floor(d2dest))
        LODESTONES[bestL.n].Teleport()
        API.RandomSleep2(2000, 500, 500)
    end
    QUEST.MoveTo(dx, dy, dz or 0, tol or 5)
end

-- Step 0: Start quest
-- Note: Talk to Malignius Mortifer next to the ritual site.
qs:step(0, "Start quest", function()
    Interact:NPC("Malignius Mortifer", "Talk to")
    QUEST:DialogSeq({1}, 10)
    API.DoAction_Interface(0x24,0xffffffff,1,1500,409,-1,API.OFF_ACT_GeneralInterface_route)
    QUEST:DialogSeq({4}, 10)
end)

-- Step 5: Make impure essences
-- Note: Have 2 change runes and 2 elemental runes on the ritual, then interact.
qs:step(5, "Make impure essences", function()
    API.DoAction_Object1(0x29, API.OFF_ACT_GeneralObject_route0, {127326}, 50)
    API.DoAction_Interface(0xffffffff,0xffffffff,1,1224,34,13,API.OFF_ACT_GeneralInterface_route)
    API.DoAction_Interface(0x24,0xffffffff,1,1224,44,-1,API.OFF_ACT_GeneralInterface_route)
    Interact:Object("Platform", "Start ritual")
    API.RandomSleep2(60000, 6000, 6000)
end)

-- Step 15: Collect impure essences
-- Note: Attempt to make some spirit runes.
qs:step(15, "Collect impure essences", function()
    Interact:Object("Ritual chest", "Open")
    API.DoAction_Interface(0xffffffff,0xd973,1,168,35,7,API.OFF_ACT_GeneralInterface_route)
end)

-- Step 20: Talk to Rasial
-- Note: Interact with Rasial, the First Necromancer.
qs:step(20, "Talk to Rasial, the First Necromancer", function()
    smartWalk(1164, 1822, 1, 5)
    Interact:Object("Dark portal", "Enter")
    Interact:NPC("Rasial, the First Necromancer", "Talk to")
    QUEST:DialogSeq({}, 10)
end)

-- Step 22: Craft runes
-- Note: Craft your runes at the Spirit altar.
qs:step(22, "Craft your runes", function()
    QUEST:DialogSeq({}, 10)
    Interact:Object("Spirit altar", "Craft runes")
end)

-- Step 25: Finish up
-- Note: Head back to Malignius to complete the quest.
qs:step(25, "Finish up", function()
    Interact:Object("Dark portal", "Exit")
    smartWalk(1039, 1769, 1, 5)
    Interact:NPC("Malignius Mortifer", "Talk to")
    QUEST:DialogSeq({1}, 10)
end)

qs:onComplete(function()
    API.logInfo("[QUEST] Rune Mythos complete!")
    API.Write_LoopyLoop(false)
end)

API.Write_fake_mouse_do(false)
API.SetMaxIdleTime(10)

qs:run()
